#we use java
language: java

#we add the java development kit (jdk)
jdk:
- openjdk8
services:
#Linking Travis CI and Docker
- docker
# SonarCloud
addons:
  sonarcloud:
    organization: "cicd-applied-to-spring-boot-java-app"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

before_install:
- mvn clean
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk-alpine


